openapi: 3.0.0
info:
  title: HMIS User Service
  version: 1.0.0
  description: |
       **Note :**
              Please note that the partial updates are supported via PUT APIs. However, Note that If "null" value is passed for any element, in the PUT request body, it will be ignored. An empty string value should be sent (instead of "null" value) for the elements that need to be updated with NULL values.
servers:
  - url: 'https://www.hslynk.com/hmis-user-service/rest'
paths:
  /accounts:
    post:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
        '409':
          description: An account with the specified username already exists.
          content:
            application/json:
              schema:
                type: object
      description: >
        It creates an account with the specified username and sends out an email
        to the user to verify the account creation. The initial status of the
        newly created account is PENDING. The status is changed to ACTIVE when
        the user verifies account creation by clicking the link embedded in the
        email. Only an ACTIVE account can log-in using the Create a session
        (Log-in) API. <br> It returns an error if an account with the specified
        username already exists.

        This endpoint does the following:

        1) If request does not contain profile information, standard profile
        will be assigned to the user.

        2) If request does not contain role information, default role will be
        assigned based on profile.    

        3) Project Group of the user will be same as the project group of
        logged-in user who creates the account.

        The user must have "USR_CREATE_ACCOUNT" permission to use this API    
      operationId: POST_accounts
      parameters:
        - name: Authorization
          in: header
          required: true
          description: >-
            Authorization request header should specify as HMISUserAuth
            session_token={sessiontokenvalue}.
          schema:
            type: string
        - name: X-HMIS-TrustedApp-Id
          in: header
          required: true
          description: Trusted App id should be provide in this header.
          schema:
            type: string
    get:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      description: To get all the users under logged in your project group.
      operationId: GET_accounts
      parameters:
        - name: Authorization
          in: header
          required: true
          description: >-
            Authorization request header should specify as HMISUserAuth
            session_token={sessiontokenvalue}.
          schema:
            type: string
        - name: X-HMIS-TrustedApp-Id
          in: header
          required: true
          description: Trusted App id should be provide in this header.
          schema:
            type: string
        - name: startIndex
          in: query
          schema:
            default: '0'
            type: string
        - name: maxItems
          in: query
          schema:
            default: '30'
            type: string
  '/accounts/{accountid}':
    put:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      description: >
        To update a specific account information.

        Provide account id as path variable for upatading non loggedin user. If
        need to update logged in user send self as account id.
      operationId: PUT_accounts-accountid
    get:
      responses:
        '200':
          description: |
            Successfully retrieved resource(s)
          content:
            application/json:
              schema:
                type: object
        '403':
          description: ''
          content:
            application/json:
              schema:
                type: object
      description: |
        Gets (aka reads or retrieves) a specific account. <BR><br>
        GET /accounts/{username}
        <b>
      operationId: GET_accounts-accountid
      parameters:
        - name: Authorization
          in: header
          required: true
          description: >-
            Authorization request header should specify as HMISUserAuth
            session_token={sessiontokenvalue}.
          schema:
            type: string
        - name: X-HMIS-TrustedApp-Id
          in: header
          required: true
          description: Trusted App id should be provide in this header.
          schema:
            type: string
    delete:
      responses:
        default:
          description: ''
      description: |
        Account status will be updated to DELETED. 
      operationId: DELETE_accounts-accountid
      parameters:
        - name: Authorization
          in: header
          required: true
          description: >-
            Authorization request header should specify as HMISUserAuth
            session_token={sessiontokenvalue}.
          schema:
            type: string
        - name: X-HMIS-TrustedApp-Id
          in: header
          required: true
          description: Trusted App id should be provide in this header.
          schema:
            type: string
    parameters:
      - name: accountid
        in: path
        required: true
        schema:
          type: string
  '/accounts/{accountid}/activate':
    put:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
        '403':
          description: ''
          content:
            application/json:
              schema:
                type: object
      description: |
        To reactivate a specified user account
      operationId: PUT_accounts-accountid-activate
      parameters:
        - name: Authorization
          in: header
          required: true
          description: >-
            Authorization request header should specify as HMISUserAuth
            session_token={sessiontokenvalue}.
          schema:
            type: string
        - name: X-HMIS-TrustedApp-Id
          in: header
          required: true
          description: Trusted App id should be provide in this header.
          schema:
            type: string
    parameters:
      - name: accountid
        in: path
        required: true
        schema:
          type: string
  '/accounts/{accountid}/activate/basicinfo':
    get:
      responses:
        '200':
          description: |
            Successfully retrieved resource(s)
          content:
            application/json:
              schema:
                type: object
        '403':
          description: ''
          content:
            application/json:
              schema:
                type: object
      description: |
        Gets (aka reads or retrieves) a specific account. <BR><br>
        GET /accounts/{username}
        <b>
      operationId: GET_accounts-accountid-activate-basicinfo
      parameters:
        - name: Authorization
          in: header
          required: true
          description: >-
            Authorization request header should specify as HMISUserAuth
            session_token={sessiontokenvalue}.
          schema:
            type: string
        - name: X-HMIS-TrustedApp-Id
          in: header
          required: true
          description: Trusted App id should be provide in this header.
          schema:
            type: string
    parameters:
      - name: accountid
        in: path
        required: true
        schema:
          type: string
  '/accounts/{accountid}/activate/passwordchanges':
    put:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
        '403':
          description: ''
          content:
            application/json:
              schema:
                type: object
      description: >
        Changes password for an account. To change the password, the user must
        be logged-in and provide his/her current password.

        The {username} is a value that uniquely identifies an account.

        To change the password of the currently logged-in user, the {username}
        can be replaced by <b>self</b> keyword in the URL as shown below.

        <b>POST</b> /accounts/self/passwordchanges
      operationId: PUT_accounts-accountid-activate-passwordchanges
      parameters:
        - name: Authorization
          in: header
          required: true
          description: >-
            Authorization request header should specify as HMISUserAuth
            session_token={sessiontokenvalue}.
          schema:
            type: string
        - name: X-HMIS-TrustedApp-Id
          in: header
          required: true
          description: Trusted App id should be provide in this header.
          schema:
            type: string
    parameters:
      - name: accountid
        in: path
        required: true
        schema:
          type: string
  '/accounts/{accountid}/activate/forgotpassword':
    post:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
        '403':
          description: ''
          content:
            application/json:
              schema:
                type: object
        '404':
          description: ''
          content:
            application/json:
              schema:
                type: object
      description: >
        Resets password for an account. It sends out an email notification to
        the user to verify the password reset. The new password becomes
        effective only after it has been verified by the user. It returns an
        error if an account with the specified username does not exist OR the
        account has been DISABLED.

        </br> The {username} is a value that uniquely identifies an account.
      operationId: POST_accounts-accountid-activate-forgotpassword
      parameters:
        - name: Authorization
          in: header
          required: true
          description: >-
            Authorization request header should specify as HMISUserAuth
            session_token={sessiontokenvalue}.
          schema:
            type: string
        - name: X-HMIS-TrustedApp-Id
          in: header
          required: true
          description: Trusted App id should be provide in this header.
          schema:
            type: string
    parameters:
      - name: accountid
        in: path
        required: true
        schema:
          type: string
  '/accounts/{accountid}/roles':
    put:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
        '404':
          description: ''
          content:
            application/json:
              schema:
                type: object
      description: >-
        To assigne a role to user. If the role is already assigned nothing will
        happen.
      operationId: PUT_accounts-accountid-roles
      parameters:
        - name: Authorization
          in: header
          required: true
          description: >-
            Authorization request header should specify as HMISUserAuth
            session_token={sessiontokenvalue}.
          schema:
            type: string
        - name: X-HMIS-TrustedApp-Id
          in: header
          required: true
          description: Trusted App id should be provide in this header.
          schema:
            type: string
    parameters:
      - name: accountid
        in: path
        required: true
        schema:
          type: string
  '/accounts/{accountid}/roles/{roleid}':
    delete:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
        '403':
          description: ''
          content:
            application/json:
              schema:
                type: object
        '404':
          description: ''
          content:
            application/json:
              schema:
                type: object
      description: To remove role from the user.
      operationId: DELETE_accounts-accountid-roles-roleid
      parameters:
        - name: Authorization
          in: header
          required: true
          description: >-
            Authorization request header should specify as HMISUserAuth
            session_token={sessiontokenvalue}.
          schema:
            type: string
        - name: X-HMIS-TrustedApp-Id
          in: header
          required: true
          description: Trusted App id should be provide in this header.
          schema:
            type: string
    parameters:
      - name: roleid
        in: path
        required: true
        schema:
          type: string
      - name: accountid
        in: path
        required: true
        schema:
          type: string
  /profiles:
    get:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                example : 
                          profiles:
                            pagination:
                              from: 0
                              returned: 3
                              total: 7
                              maximum: 30
                              sort: {}
                            profile:
                            - profileName: Standard Profile
                              profileDescription: Standard Profile
                              apiMethods: []
                              id: 004aed07-b4d4-4696-b8f6-1607f6f49bac
                            - profileName: Developer Profile
                              profileDescription: Developer Profile
                              apiMethods: []
                              id: 1ebd9476-600c-463f-8c3d-bf8accad472b
                            - profileName: Super Admin Profile
                              profileDescription: Super Admin Profile
                              apiMethods: []
                              id: b67c38a1-2762-4393-b69b-41a0a11e6efc

      description: To get all Profiles
      operationId: GET_profiles
      parameters:
        - name: Authorization
          in: header
          required: true
          description: >-
            Authorization request header should specify as HMISUserAuth
            session_token={sessiontokenvalue}.
          schema:
            type: string
        - name: X-HMIS-TrustedApp-Id
          in: header
          required: true
          description: Trusted App id should be provide in this header.
          schema:
            type: string
        - name: startIndex
          in: query
          schema:
            default: '0'
            type: string
        - name: maxItems
          in: query
          schema:
            default: '30'
            type: string
    post:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      description: Create a new profile
      operationId: POST_profiles
      parameters:
        - name: Authorization
          in: header
          required: true
          description: >-
            Authorization request header should specify as HMISUserAuth
            session_token={sessiontokenvalue}.
          schema:
            type: string
        - name: X-HMIS-TrustedApp-Id
          in: header
          required: true
          description: Trusted App id should be provide in this header.
          schema:
            type: string
  '/profiles/{profileId}':
    put:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
        '404':
          description: ''
          content:
            application/json:
              schema:
                type: object
      description: To Update A specific Profile.
      operationId: PUT_profiles-profileId
      parameters:
        - name: Authorization
          in: header
          required: true
          description: >-
            Authorization request header should specify as HMISUserAuth
            session_token={sessiontokenvalue}.
          schema:
            type: string
        - name: X-HMIS-TrustedApp-Id
          in: header
          required: true
          description: Trusted App id should be provide in this header.
          schema:
            type: string
    delete:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
        '404':
          description: ''
          content:
            application/json:
              schema:
                type: object
      description: |
        To Delete A specific Profile
      operationId: DELETE_profiles-profileId
      parameters:
        - name: Authorization
          in: header
          required: true
          description: >-
            Authorization request header should specify as HMISUserAuth
            session_token={sessiontokenvalue}.
          schema:
            type: string
        - name: X-HMIS-TrustedApp-Id
          in: header
          required: true
          description: Trusted App id should be provide in this header.
          schema:
            type: string
    get:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
        '404':
          description: ''
          content:
            application/json:
              schema:
                type: object
      description: To get a Specific Profile Details
      operationId: GET_profiles-profileId
      parameters:
        - name: Authorization
          in: header
          required: true
          description: >-
            Authorization request header should specify as HMISUserAuth
            session_token={sessiontokenvalue}.
          schema:
            type: string
        - name: X-HMIS-TrustedApp-Id
          in: header
          required: true
          description: Trusted App id should be provide in this header.
          schema:
            type: string
    parameters:
      - name: profileId
        in: path
        required: true
        schema:
          type: string
  /sharingrules:
    post:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
        '404':
          description: ''
          content:
            application/json:
              schema:
                type: object
      description: Create a new sharing rule.
      operationId: POST_sharingrules
      parameters:
        - name: Authorization
          in: header
          required: true
          description: >-
            Authorization request header should specify as HMISUserAuth
            session_token={sessiontokenvalue}.
          schema:
            type: string
        - name: X-HMIS-TrustedApp-Id
          in: header
          required: true
          description: Trusted App id should be provide in this header.
          schema:
            type: string
  '/sharingrules/{sharingruleid}':
    put:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
        '404':
          description: ''
          content:
            application/json:
              schema:
                type: object
      description: To update a specifc Sharing Rule
      operationId: PUT_sharingrules-sharingruleid
      parameters:
        - name: Authorization
          in: header
          required: true
          description: >-
            Authorization request header should specify as HMISUserAuth
            session_token={sessiontokenvalue}.
          schema:
            type: string
        - name: X-HMIS-TrustedApp-Id
          in: header
          required: true
          description: Trusted App id should be provide in this header.
          schema:
            type: string
    delete:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
        '404':
          description: ''
          content:
            application/json:
              schema:
                type: object
      description: To Delete A Specifc Sharing Rule
      operationId: DELETE_sharingrules-sharingruleid
      parameters:
        - name: Authorization
          in: header
          required: true
          description: >-
            Authorization request header should specify as HMISUserAuth
            session_token={sessiontokenvalue}.
          schema:
            type: string
        - name: X-HMIS-TrustedApp-Id
          in: header
          required: true
          description: Trusted App id should be provide in this header.
          schema:
            type: string
    parameters:
      - name: sharingruleid
        in: path
        required: true
        schema:
          type: string
  /roles:
    get:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      description: To get All the roles.
      operationId: GET_roles
      parameters:
        - name: Authorization
          in: header
          required: true
          description: >-
            Authorization request header should specify as HMISUserAuth
            session_token={sessiontokenvalue}.
          schema:
            type: string
        - name: X-HMIS-TrustedApp-Id
          in: header
          required: true
          description: Trusted App id should be provide in this header.
          schema:
            type: string
        - name: startIndex
          in: query
          schema:
            default: '0'
            type: string
        - name: maxItems
          in: query
          schema:
            default: '30'
            type: string
    post:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      description: To create A new role
      operationId: POST_roles
      parameters:
        - name: Authorization
          in: header
          required: true
          description: >-
            Authorization request header should specify as HMISUserAuth
            session_token={sessiontokenvalue}.
          schema:
            type: string
        - name: X-HMIS-TrustedApp-Id
          in: header
          required: true
          description: Trusted App id should be provide in this header.
          schema:
            type: string
  '/roles/{roleid}':
    put:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
        '404':
          description: ''
          content:
            application/json:
              schema:
                type: object
      description: To update a specific role
      operationId: PUT_roles-roleid
      parameters:
        - name: Authorization
          in: header
          required: true
          description: >-
            Authorization request header should specify as HMISUserAuth
            session_token={sessiontokenvalue}.
          schema:
            type: string
        - name: X-HMIS-TrustedApp-Id
          in: header
          required: true
          description: Trusted App id should be provide in this header.
          schema:
            type: string
    delete:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
        '404':
          description: ''
          content:
            application/json:
              schema:
                type: object
      description: To delete a Specific role
      operationId: DELETE_roles-roleid
      parameters:
        - name: Authorization
          in: header
          required: true
          description: >-
            Authorization request header should specify as HMISUserAuth
            session_token={sessiontokenvalue}.
          schema:
            type: string
        - name: X-HMIS-TrustedApp-Id
          in: header
          required: true
          description: Trusted App id should be provide in this header.
          schema:
            type: string
    parameters:
      - name: roleid
        in: path
        required: true
        schema:
          type: string
  /permissionsets:
    post:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
      description: To create a new Permission Set.
      operationId: POST_permissionsets
      parameters:
        - name: Authorization
          in: header
          required: true
          description: >-
            Authorization request header should specify as HMISUserAuth
            session_token={sessiontokenvalue}.
          schema:
            type: string
        - name: X-HMIS-TrustedApp-Id
          in: header
          required: true
          description: Trusted App id should be provide in this header.
          schema:
            type: string
  '/permissionsets/{permissionsetid}':
    put:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
        '404':
          description: ''
          content:
            application/json:
              schema:
                type: object
      description: To update a Specific Permission Set
      operationId: PUT_permissionsets-permissionsetid
      parameters:
        - name: Authorization
          in: header
          required: true
          description: >-
            Authorization request header should specify as HMISUserAuth
            session_token={sessiontokenvalue}.
          schema:
            type: string
        - name: X-HMIS-TrustedApp-Id
          in: header
          required: true
          description: Trusted App id should be provide in this header.
          schema:
            type: string
    delete:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
        '404':
          description: ''
          content:
            application/json:
              schema:
                type: object
      description: To Delete a specific Permission Set
      operationId: DELETE_permissionsets-permissionsetid
      parameters:
        - name: Authorization
          in: header
          required: true
          description: >-
            Authorization request header should specify as HMISUserAuth
            session_token={sessiontokenvalue}.
          schema:
            type: string
        - name: X-HMIS-TrustedApp-Id
          in: header
          required: true
          description: Trusted App id should be provide in this header.
          schema:
            type: string
    get:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
        '404':
          description: ''
          content:
            application/json:
              schema:
                type: object
      description: To get Details About a specific Permision Set
      operationId: GET_permissionsets-permissionsetid
      parameters:
        - name: Authorization
          in: header
          required: true
          description: >-
            Authorization request header should specify as HMISUserAuth
            session_token={sessiontokenvalue}.
          schema:
            type: string
        - name: X-HMIS-TrustedApp-Id
          in: header
          required: true
          description: Trusted App id should be provide in this header.
          schema:
            type: string
    parameters:
      - name: permissionsetid
        in: path
        required: true
        schema:
          type: string
  '/permissionsets/{username}/permissionsetassignments':
    post:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
        '404':
          description: ''
          content:
            application/json:
              schema:
                type: object
      description: |
        To Assign a Permission to A user
         <b>Note:</b> /permissionset/hmisuser/assignPermissionSet
      operationId: POST_permissionsets-username-permissionsetassignments
      parameters:
        - name: Authorization
          in: header
          required: true
          description: >-
            Authorization request header should specify as HMISUserAuth
            session_token={sessiontokenvalue}.
          schema:
            type: string
        - name: X-HMIS-TrustedApp-Id
          in: header
          required: true
          description: Trusted App id should be provide in this header.
          schema:
            type: string
    parameters:
      - name: username
        in: path
        required: true
        schema:
          type: string
  /informationreleases:
    post:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
        '404':
          description: ''
          content:
            application/json:
              schema:
                type: object
      description: To create a release information for a enrollment.
      operationId: POST_informationreleases
      parameters:
        - name: Authorization
          in: header
          required: true
          description: >-
            Authorization request header should specify as HMISUserAuth
            session_token={sessiontokenvalue}.
          schema:
            type: string
        - name: X-HMIS-TrustedApp-Id
          in: header
          required: true
          description: Trusted App id should be provide in this header.
          schema:
            type: string
  '/informationreleases/{enrollmentId}':
    put:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
        '404':
          description: ''
          content:
            application/json:
              schema:
                type: object
      description: To update an enrollment's release of information.
      operationId: PUT_informationreleases-enrollmentId
      parameters:
        - name: Authorization
          in: header
          required: true
          description: >-
            Authorization request header should specify as HMISUserAuth
            session_token={sessiontokenvalue}.
          schema:
            type: string
        - name: X-HMIS-TrustedApp-Id
          in: header
          required: true
          description: Trusted App id should be provide in this header.
          schema:
            type: string
    delete:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
        '404':
          description: ''
          content:
            application/json:
              schema:
                type: object
      description: To delete an enrollment's release of information.
      operationId: DELETE_informationreleases-enrollmentId
      parameters:
        - name: Authorization
          in: header
          required: true
          description: >-
            Authorization request header should specify as HMISUserAuth
            session_token={sessiontokenvalue}.
          schema:
            type: string
        - name: X-HMIS-TrustedApp-Id
          in: header
          required: true
          description: Trusted App id should be provide in this header.
          schema:
            type: string
    get:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
        '404':
          description: ''
          content:
            application/json:
              schema:
                type: object
      description: To get an enrollment's release of information.
      operationId: GET_informationreleases-enrollmentId
      parameters:
        - name: Authorization
          in: header
          required: true
          description: >-
            Authorization request header should specify as HMISUserAuth
            session_token={sessiontokenvalue}.
          schema:
            type: string
        - name: X-HMIS-TrustedApp-Id
          in: header
          required: true
          description: Trusted App id should be provide in this header.
          schema:
            type: string
        - name: startIndex
          in: query
          schema:
            default: '0'
            type: string
        - name: maxItems
          in: query
          schema:
            default: '30'
            type: string
    parameters:
      - name: enrollmentId
        in: path
        required: true
        schema:
          type: string
  /projectgroups:
    post:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                example :

      description: |
        To create a new project group.
      operationId: POST_projectgroups
      parameters:
        - name: Authorization
          in: header
          required: true
          description: >-
            Authorization request header should specify as HMISUserAuth
            session_token={sessiontokenvalue}.
          schema:
            type: string
        - name: X-HMIS-TrustedApp-Id
          in: header
          required: true
          description: Trusted App id should be provide in this header.
          schema:
            type: string
    get:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                example: 
                        projectgroups:
                            pagination:
                              from: 0
                              returned: 19
                              total: 19
                              maximum: 30
                              sort: {}
                            projectGroups:
                            - projectGroupName: CK Project
                              projectGroupDesc: Test CK Project
                              projectGroupId: 34926f5a-3bc6-42af-ba30-9f0a9746316d
                              projectGroupCode: CP0004
                              skipuseridentifers: false
                              bucketName: cp0004-6546a3c1-5cc3-4d9c-afd6-691a2704d8b9
                              projects: []
                            - projectGroupName: Skid Row Housing Trust
                              projectGroupDesc: Project group for Skid Row Housing Trust
                              projectGroupId: c1bc338e-89c9-4dad-a0a1-12cbbec9c1c4
                              projectGroupCode: SR0012
                              skipuseridentifers: false
                              bucketName: sr0014-332894dd-eaff-4308-9c51-49ffb924131b
                              projects: []
      description: To retrive existing project groups.
      operationId: GET_projectgroups
      parameters:
        - name: Authorization
          in: header
          required: true
          description: >-
            Authorization request header should specify as HMISUserAuth
            session_token={sessiontokenvalue}.
          schema:
            type: string
        - name: X-HMIS-TrustedApp-Id
          in: header
          required: true
          description: Trusted App id should be provide in this header.
          schema:
            type: string
        - name: startIndex
          in: query
          schema:
            default: '0'
            type: string
        - name: maxItems
          in: query
          schema:
            default: '30'
            type: string
  '/projectgroups/{projectgroupid}':
    put:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
        '404':
          description: ''
          content:
            application/json:
              schema:
                type: object
      description: >-
        To update existing project group. While updating project group, api will
        remove all the assigned projects and add projects which are in new
        request body.
      operationId: PUT_projectgroups-projectgroupid
      parameters:
        - name: Authorization
          in: header
          required: true
          description: >-
            Authorization request header should specify as HMISUserAuth
            session_token={sessiontokenvalue}.
          schema:
            type: string
        - name: X-HMIS-TrustedApp-Id
          in: header
          required: true
          description: Trusted App id should be provide in this header.
          schema:
            type: string
    delete:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
        '404':
          description: ''
          content:
            application/json:
              schema:
                type: object
      description: To remove existing project group.
      operationId: DELETE_projectgroups-projectgroupid
      parameters:
        - name: Authorization
          in: header
          required: true
          description: >-
            Authorization request header should specify as HMISUserAuth
            session_token={sessiontokenvalue}.
          schema:
            type: string
        - name: X-HMIS-TrustedApp-Id
          in: header
          required: true
          description: Trusted App id should be provide in this header.
          schema:
            type: string
    get:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
        '404':
          description: ''
          content:
            application/json:
              schema:
                type: object
      description: To retrieve selected project group.
      operationId: GET_projectgroups-projectgroupid
      parameters:
        - name: Authorization
          in: header
          required: true
          description: >-
            Authorization request header should specify as HMISUserAuth
            session_token={sessiontokenvalue}.
          schema:
            type: string
        - name: X-HMIS-TrustedApp-Id
          in: header
          required: true
          description: Trusted App id should be provide in this header.
          schema:
            type: string
    parameters:
      - name: projectgroupid
        in: path
        required: true
        schema:
          type: string
  /apimethodauthcheck/{apimethodid}:
    parameters:
    - name: Authorization
      in: header
      required: true
      description: >-
        Authorization request header should specify as HMISUserAuth
        session_token={sessiontokenvalue}.
      schema:
        type: string
    - name: X-HMIS-TrustedApp-Id
      in: header
      required: true
      description: Trusted App id should be provide in this header.
      schema:
        type: string
    - name: apimethodid
      in: path
      required: true
      description: API method id
      schema:
        type: string
    get:
      responses:
        '200':
          description: ''
          content:
           application/json:
            schema:
              example:
                      apiMethodAuthorizationCheck:
                        trustedAppId: MASTER_TRUSTED_APP
                        accessToken: F29B405D91A648659F896F29B05D609446D1D2E9494648079AC2267499CD75A5
                        apiMethodId: USR_CHECK_API_AUTHORIZATION
                        trustedApp:
                          trustedAppId: MASTER_TRUSTED_APP
                          friendlyName: MASTER_TRUSTED_APP
                          description: MASTER_TRUSTED_APP
                          status: ACTIVE
                          trustedAppFamilyType: APP
                          trustedAppProfileType: NATIVE
                        account:
                          accountId: 8b6c6ef2-87c7-47f0-8874-4cca6f09365c
                          username: superadmin@hmis.com
                          emailAddress: hmisprojects@gmail.com
                          firstName: Surya
                          middleName: middle
                          lastName: Yadavalli
                          gender: 0
                          status: ACTIVE
                          twoFactorAuthentication: false
                          projectGroup:
                            projectGroupName: PROJECT_GROUP_NAME
                            projectGroupDesc: PROJECT_GROUP_DESCRIPTION
                            projectGroupId: 9b9792ca-8730-4d21-9a39-6902229fd4b9
                            projectGroupCode: PG0001
                            skipuseridentifers: false
                            bucketName: pg0001-6546a3c1-5cc3-4d9c-afd6-691a2704d8b9
                            senderEmail: mc211_support@ctagroup.org
                            projects: []
                          profile:
                            profileName: Super Admin Profile
                            profileDescription: Super Admin Profile
                            apiMethods: []
                            id: b67c38a1-2762-4393-b69b-41a0a11e6efc
                          roles:
                          - id: b67c38a1-2762-4393-b69b-41a0a11e6efc
                            roleName: SUPERADMIN
                            roleDescription: Super Admin Role
                        checkSessionToken: true
              
        '401':
          description: ''
          content:
            application/json:
              schema:
                example:
                            errors:
                                error:
                                - code: INVALID_SESSION_TOKEN
                                  message: 'token has expired: 11B88EAFF0184196A846A54CFB35BDEB4BD06E79BB9145F78524FC37A3F0DE63'          
components:
  schemas: {}
  responses: {}
  parameters: {}
  examples: {}
  requestBodies: {}
  headers: {}
  securitySchemes:
    oauth_2_0:
      description: |
        The HMIS API supports OAuth 2.0 for authenticating all API requests.
      type: oauth2
      flows:
        password:
          tokenUrl: 'https://hslynk.com/hmis-authorization-service/rest/token'
          scopes:
            user: ''
            administrator: ''
  links: {}
  callbacks: {}